# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
  format_listener:
    rules:
      - { path: ^/,priorities: ['json'], fallback_format: json,  }
  serializer:
    serialize_null: true


  exception:
      enabled: true
  param_fetcher_listener: true



  view:
    view_response_listener: 'force'
    formats:
      json: true






